### ISSUE TITLE
Drupal Segment Fault: 11 error caused by to many .info files

### ISSUE THREAD

**Issue by devtype** [frontend-united/generator-drupal-theme#22]
Hi,

I love the way Drupal is going with this.
I found an error but lucky someone already hat a fix setup :)

Apparently if there are to many .info files present Drupal will run into some problems like falling to clear cache. To avoid that it was suggested to move the node_modules folder into a hidden folder in the theme .npm so that Drupal dose not track it. This also needs some adjustments on behalf of the gulpfile.js since the path need fixing. To prevent people from running into this maybe it would be best that this is done in the setup rather than fixing it afterwards. I added the link fore the Drupal issue see comment 5

https://www.drupal.org/node/2309023#comment-9061593

**Comment by iamcarrico** [comment]
The node_modules folder cannot be changed— and the solution for this has already been discussed on D.o: https://www.drupal.org/node/2329453
